In [5]:
import pandas as pd
import numpy as np

# df_dados = pd.read_csv("Dados.csv")
filmes = pd.read_csv("Filmes.csv", sep=",")
ratings = pd.read_csv("Ratings.csv", sep=";")
# df_tags = pd.read_csv("Tags.csv")

ratings.head()

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [6]:
df = filmes.merge(ratings, on="movieId")
df.head()

,movieId,title,genres,year,userId,rating
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,1,4.0
1,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,5,4.0
2,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,7,4.5
3,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,15,2.5
4,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,17,4.5

In [7]:
tabela_filmes = pd.pivot_table(df, index="title", columns="userId", values="rating").fillna(0)
tabela_filmes.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
'71,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
'Hellboy': The Seeds of Creation,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Salem's Lot,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Til There Was You,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
import sklearn.metrics.pairwise as pw

In [9]:
rec = pw.cosine_similarity(tabela_filmes)
rec_df = pd.DataFrame(rec, columns=tabela_filmes.index, index=tabela_filmes.index)
rec_df.head()

C:\Users\diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\extmath.py:193: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

title,'71,'Hellboy': The Seeds of Creation,'Round Midnight,'Salem's Lot,'Til There Was You,'Tis the Season for Love,"'burbs, The",'night Mother,(500) Days of Summer,*batteries not included,...,Zulu,[REC],[REC]²,[REC]³ 3 Génesis,anohana: The Flower We Saw That Day - The Movie,eXistenZ,xXx,xXx: State of the Union,¡Three Amigos!,À nous la liberté (Freedom for Us)
title,,,,,,,,,,,,,,,,,,,,,
'71,1.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.141653,0.0,...,0.0,0.342055,0.543305,0.707107,0.0,0.0,0.139431,0.327327,0.0,0.0
'Hellboy': The Seeds of Creation,0.0,1.000000,0.707107,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Round Midnight,0.0,0.707107,1.000000,0.000000,0.000000,0.0,0.176777,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Salem's Lot,0.0,0.000000,0.000000,1.000000,0.857493,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Til There Was You,0.0,0.000000,0.000000,0.857493,1.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0

In [10]:
cossine_df = pd.DataFrame(rec_df["Goodfellas"].sort_values(ascending=False))
cossine_df.columns = ["Recomendações"]
cossine_df.head(20)

                                                Recomendações
title
Goodfellas                                           1.000000
Reservoir Dogs                                       0.674264
Godfather, The                                       0.664841
Godfather: Part II, The                              0.621549
Fargo                                                0.609887
Pulp Fiction                                         0.596707
Usual Suspects, The                                  0.580006
Apocalypse Now                                       0.575341
American History X                                   0.574528
Full Metal Jacket                                    0.571657
Fight Club                                           0.569371
American Beauty                                      0.559208
Shining, The                                         0.540206
Big Lebowski, The                                    0.530201
Star Wars: Episode V - The Empire Strikes Back       0.526066
Silence of the Lambs, The                            0.520433
Ferris Bueller's Day Off                             0.520108
Clockwork Orange, A                                  0.515941
One Flew Over the Cuckoo's Nest                      0.514512
Taxi Driver                                          0.513317

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [12]:
dados = pd.read_csv("Dados.csv")
tags = pd.read_csv("Tags.csv")

In [13]:
dados.head()

,Name,Year,Stars,Score,Time,Votes,Total,Tags,Directors_Cast,Discription
0,Pulp Fiction,1994,8.9,94.0,154,"1,871,051",$107.93,\nCrime Drama,Quentin Tarantino John Travolta Uma Thurman Sa...,\nThe lives of two mob hitmen a boxer a gangst...
1,The Amazing Spider-Man 2,2014,6.6,53.0,142,"425,529",$202.85,\nAction Adventure Fantasy,Marc Webb Andrew Garfield Emma Stone Jamie Fox...,\nWhen New York is put under siege by Oscorp i...
2,The Shawshank Redemption,1994,9.3,80.0,142,"2,409,436",$28.34,\nDrama,Frank Darabont Tim Robbins Morgan Freeman Bob ...,\nTwo imprisoned men bond over a number of yea...
3,Star Wars: Episode IV - A New Hope,1977,8.6,90.0,121,"1,255,464",$322.74,\nAction Adventure Fantasy,George Lucas Mark Hamill Harrison Ford Carrie ...,\nLuke Skywalker joins forces with a Jedi Knig...
4,Back to the Future,1985,8.5,87.0,116,"1,087,878",$210.61,\nAdventure Comedy Sci-Fi,Robert Zemeckis Michael J. Fox Christopher Llo...,\nMarty McFly a 17-year-old high school studen...

In [14]:
tags.head()

  movieId                                                tag
0       1  Owned,imdb top 250,Pixar,Pixar,time travel,chi...
1       2  Robin Williams,time travel,fantasy,based on ch...
2       3  funny,best friend,duringcreditsstinger,fishing...
3       4  based on novel or book,chick flick,divorce,int...
4       5  aging,baby,confidence,contraception,daughter,g...

In [15]:
filmes["movieId"] = filmes["movieId"].apply(lambda x: str(x))

In [16]:
df2 = filmes.merge(dados, left_on="title", right_on="Name", how="left")
df2 = df2.merge(tags, left_on="movieId", right_on="movieId", how="left")

df2["Infos"] = df2["genres"] + str(df2["Directors_Cast"]) + str(df2["Discription"]) + df2["tag"]

df2.head()

,movieId,title,genres,year,Name,Year,Stars,Score,Time,Votes,Total,Tags,Directors_Cast,Discription,tag,Infos
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,Toy Story,1995,8.3,95.0,81,"908,794",$191.80,\nAnimation Adventure Comedy,John Lasseter Tom Hanks Tim Allen Don Rickles ...,\nA cowboy doll is profoundly threatened and j...,"Owned,imdb top 250,Pixar,Pixar,time travel,chi...",Adventure|Animation|Children|Comedy|Fantasy0 ...
1,2,Jumanji,Adventure|Children|Fantasy,1995,Jumanji,1995,7.0,39.0,104,"316,485",$100.48,\nAdventure Comedy Family,Joe Johnston Robin Williams Kirsten Dunst Bonn...,\nWhen two kids find and play a magical board ...,"Robin Williams,time travel,fantasy,based on ch...",Adventure|Children|Fantasy0 John Lasset...
2,3,Grumpier Old Men,Comedy|Romance,1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"funny,best friend,duringcreditsstinger,fishing...",Comedy|Romance0 John Lasseter Tom Hanks...
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995,Waiting to Exhale,1995,6.0,NaN,124,"9,911",$67.05,\nComedy Drama Romance,Forest Whitaker Whitney Houston Angela Bassett...,NaN,"based on novel or book,chick flick,divorce,int...",Comedy|Drama|Romance0 John Lasseter Tom...
4,5,Father of the Bride Part II,Comedy,1995,Father of the Bride Part II,1995,6.1,49.0,106,"35,472",$76.59,\nComedy Family Romance,Charles Shyer Steve Martin Diane Keaton Martin...,\nGeorge Banks must deal not only with the pre...,"aging,baby,confidence,contraception,daughter,g...",Comedy0 John Lasseter Tom Hanks Tim All...

In [17]:
vec = TfidfVectorizer()

tfidf = vec.fit_transform(df2["Infos"].apply(lambda x: np.str_(x)))

In [18]:
sim = cosine_similarity(tfidf)

sim

array([[1.        , 0.08465854, 0.01312877, ..., 0.01361825, 0.02186222,
        0.01361825],
       [0.08465854, 1.        , 0.02747468, ..., 0.0599022 , 0.0949832 ,
        0.0599022 ],
       [0.01312877, 0.02747468, 1.        , ..., 0.19453706, 0.21472584,
        0.19453706],
       ...,
       [0.01361825, 0.0599022 , 0.19453706, ..., 1.        , 0.68030435,
        1.        ],
       [0.02186222, 0.0949832 , 0.21472584, ..., 0.68030435, 1.        ,
        0.68030435],
       [0.01361825, 0.0599022 , 0.19453706, ..., 1.        , 0.68030435,
        1.        ]])

In [19]:
sim_df2 = pd.DataFrame(sim, columns=df2["title"], index=df2["title"])
sim_df2

title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Heat,Sabrina,Tom and Huck,Sudden Death,...,Gintama: The Movie,anohana: The Flower We Saw That Day - The Movie,Silver Spoon,Love Live! The School Idol Movie,Jon Stewart Has Left the Building,Black Butler: Book of the Atlantic,No Game No Life: Zero,Flint,Bungo Stray Dogs: Dead Apple,Andrew Dice Clay: Dice Rules
title,,,,,,,,,,,,,,,,,,,,,
Toy Story,1.000000,0.084659,0.013129,0.016002,0.033845,0.007786,0.007786,0.006416,0.052864,0.007285,...,0.099869,0.013618,0.013618,0.013618,0.013618,0.013618,0.013618,0.013618,0.021862,0.013618
Jumanji,0.084659,1.000000,0.027475,0.151885,0.103882,0.003845,0.003845,0.052921,0.087719,0.041849,...,0.076600,0.059902,0.059902,0.059902,0.059902,0.059902,0.059902,0.059902,0.094983,0.059902
Grumpier Old Men,0.013129,0.027475,1.000000,0.139910,0.196165,0.046368,0.046368,0.043952,0.131067,0.072365,...,0.179095,0.194537,0.194537,0.194537,0.194537,0.194537,0.194537,0.194537,0.214726,0.194537
Waiting to Exhale,0.016002,0.151885,0.139910,1.000000,0.278759,0.019550,0.019550,0.255034,0.314388,0.151062,...,0.373854,0.407665,0.407665,0.407665,0.407665,0.407665,0.407665,0.407665,0.448173,0.407665
Father of the Bride Part II,0.033845,0.103882,0.196165,0.278759,1.000000,0.011208,0.011208,0.081509,0.261189,0.144008,...,0.356444,0.372773,0.372773,0.372773,0.372773,0.372773,0.372773,0.372773,0.427902,0.372773
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Black Butler: Book of the Atlantic,0.013618,0.059902,0.194537,0.407665,0.372773,0.015739,0.015739,0.108713,0.415254,0.220981,...,0.548640,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.680304,1.000000
No Game No Life: Zero,0.013618,0.059902,0.194537,0.407665,0.372773,0.015739,0.015739,0.108713,0.415254,0.220981,...,0.548640,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.680304,1.000000
Flint,0.013618,0.059902,0.194537,0.407665,0.372773,0.015739,0.015739,0.108713,0.415254,0.220981,...,0.548640,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.680304,1.000000
Bungo Stray Dogs: Dead Apple,0.021862,0.094983,0.214726,0.448173,0.427902,0.035105,0.035105,0.121913,0.456516,0.249018,...,0.707690,0.680304,0.680304,0.680304,0.680304,0.680304,0.680304,0.680304,1.000000,0.680304
Andrew Dice Clay: Dice Rules,0.013618,0.059902,0.194537,0.407665,0.372773,0.015739,0.015739,0.108713,0.415254,0.220981,...,0.548640,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.680304,1.000000

In [20]:
final_df = pd.DataFrame(sim_df2["Thor"].sort_values(ascending=False))

final_df.columns = ["Recomendações"]

final_df.head(20)

                                     Recomendações
title
Thor                                      1.000000
Thor: The Dark World                      0.726092
Thor: Ragnarok                            0.605341
Captain America: The First Avenger        0.574111
Avengers: Age of Ultron                   0.565323
Ant-Man                                   0.527044
Elektra                                   0.504695
Marvel One-Shot: Item 47                  0.499548
Captain America: The Winter Soldier       0.489653
Fantastic Four                            0.482729
Fantastic Four                            0.482729
Incredible Hulk, The                      0.482080
Spider-Man 2                              0.481699
Spider-Man 3                              0.475376
Avengers, The                             0.469230
Captain America: Civil War                0.468895
X-Men                                     0.440686
X2: X-Men United                          0.425301
Iron Man                                  0.425097
Ant-Man and the Wasp                      0.413056